import { Grid } from "@mui/material";
import React from "react";
import Carousel from "react-elastic-carousel";

import MultiActionAreaCard from "./IndividualCard";

function Right() {
  return (
    <Grid item xs={12} lg={8}>
      <Carousel
        enableAutoPlay={true}
        autoPlaySpeed={8000}
        breakPoints={breakPoints}
        showArrows={false}
        pagination={false}
      >
        {people?.map((data, i) => (
          <MultiActionAreaCard key={i} {...data} />
        ))}
      </Carousel>
    </Grid>
  );
}

export default Right;

 export const breakPoints = [
  { width: 1, itemsToShow: 1 },
  { width: 550, itemsToShow: 2, itemsToScroll: 2 },
  { width: 768, itemsToShow: 3 },
  { width: 1200, itemsToShow: 4 },
];

const people = [
  // {
  //   img: "https://picsum.photos/200/300",
  //   msg: ` Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque nisi
  //           aspernatur eaque consequatur facilis, fugiat quibusdam quos quis
  //           deserunt voluptates?`,
  //   name: " Mark Hurd",
  //   company: "  MDS Manufucturing",
  // },
  // {
  //   img: "https://picsum.photos/200/300",
  //   msg: ` Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque nisi
  //           aspernatur eaque consequatur facilis, fugiat quibusdam quos quis
  //           deserunt voluptates?`,
  //   name: " Joseph Hurd",
  //   company: "  XYZ Manufucturing",
  // },
  {
    img: "https://picsum.photos/200/300",
    msg: ` A leading car hiring group was pursuing faster data processing, seamless remote access, and enhanced reporting. A lot of 
          data is generated by the constantly growing number of car IT services. The big data analysis of this data is important to
          the automotive manufacturer in order to continuously improve the customer experience and achieve faster time-to-market for 
          new features at optimized cost.`,
    name: " Lilian Hurd",
    company: "  ABC Manufucturing",
  },
  {
    img: "https://picsum.photos/id/237/200/300",
    msg: ` A leading automotive group was pursuing faster data processing, seamless remote access, and enhanced reporting. A lot of 
          data is generated by the constantly growing number of car IT services. The big data analysis of this data is important to 
          the automotive manufacturer in order to continuously improve the customer experience and achieve faster time-to-market for
          new features at optimized cost.`,
    name: " Samsung Hurd",
    company: "  MTZ Manufucturing",
  },
];
